global:
  scrape_interval: 15s # Define o intervalo de raspagem para 15 segundos.

scrape_configs:
- job_name: 'prometheus' # Define um trabalho de raspagem para o próprio Prometheus.
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'rabbitmq' # Define um trabalho de raspagem para o RabbitMQ.
  static_configs:
  - targets: ['rabbitmq:15692']
